### PR TITLE
Pull request for Yamini

### PR DESCRIPTION
**Pull request by we08**

### CODE REVIEW

**Review by kurrayamini — APPROVED** [review]
Answers mentioned are fine, only one remote repository should be created for a project.

**Comment by we08** [comment]
This is to merge the answers.txt from answerbranch to master

**Comment by we08** [comment]
Reopening to close with comment

**Comment by we08** [comment]
This is to close.

**Comment by we08** [comment]
Reopening

**Comment by we08** [comment]
This will merge this time.

**Comment by we08** [comment]
Merging.

**Comment by we08** [comment]
rebase and merge

**Pull request merged**
